-- SCHEMA: staging

-- DROP SCHEMA IF EXISTS staging ;

CREATE SCHEMA IF NOT EXISTS staging
    AUTHORIZATION postgres;

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.


CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    category_id character varying COLLATE pg_catalog."default" NOT NULL,
    category "char",
    CONSTRAINT "softcartDimCategory_pkey" PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    country_id character varying COLLATE pg_catalog."default" NOT NULL,
    country "char",
    CONSTRAINT "softcartDimCountry_pkey" PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimDate"
(
    dateid character varying COLLATE pg_catalog."default" NOT NULL,
    date date,
    month character varying COLLATE pg_catalog."default",
    monthname "char",
    day character varying COLLATE pg_catalog."default",
    dayname "char",
    week "char",
    year "char",
    CONSTRAINT "softcartDimDate_pkey" PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    item_id character varying COLLATE pg_catalog."default" NOT NULL,
    item "char",
    CONSTRAINT "softcartDimItem_pkey" PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    order_id character varying NOT NULL,
    item_id character varying,
    category_id character varying,
    price numeric(2),
    country_id character varying,
    date_id character varying,
    CONSTRAINT " order_id" PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (date_id)
    REFERENCES public."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartDimItem" (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (category_id)
    REFERENCES public."softcartDimCategory" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."softcartDimCountry" (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;